[package]
name = "pegovka-messages"
version = "0.1.0"
authors = ["Dmitry Panin <dmitry.panin@getcruise.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
image = "0.23.6"
lazy_static = "1.4.0"